project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Varun Bhakri"
  page-footer:
    left: "vbhakhri@upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/vb.jpg"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.linkedin.com/in/varun-bhakhri/
        text: "LinkedIn"
      - icon: github
        href: https://github.com/vbhakhri
        text: "GitHub"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-python-code-blocks.qmd 
          - analysis/2-static-images.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb
          - analysis/RS_VB_assignment-6.ipynb



format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
